defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$OwCFPZhj$G62yjtUS2RTU0gVJ751081"]
  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"
  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
        [entryPoints.https.tls.defaultCertificate]
          certFile = "/etc/traefik/certs/cert.pem"
          keyFile = "/etc/traefik/certs/key.pem"

[api]
entrypoint="dashboard"

[docker]
domain = "oddin.localhost"
watch = true
network = "oddin-network"
