#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Creates a local Kind cluster

Usage: create-cluster [options]

Options:
  -h, --help             Show help options.
  -n, --name <VALUE>     Name for k8s cluster [default: example].
  -c, --context <VALUE>  Name for new context. Defaults to <name>-local.
EOF
)"

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR/.." || exit 1

if k3d cluster list "$name" 2> /dev/null | grep -q "$name"; then
	exit 0
fi

k3d cluster create "$name" --config config/cluster.yaml

if [[ -z "$context" ]]; then
	context="$name-local"
fi

kubectx "$context=k3d-$name"
