#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Creates a local Kind cluster

Usage: create-cluster [options]

Options:
  -h, --help            Show help options.
  -n, --name <NAME>     Name for Kind cluster [default: oddin].
  -c, --context <NAME>  Name for new context [default: asgard].
EOF
)"

# create a cluster with the local registry enabled in containerd
cat <<EOF | kind create cluster --name "$name" --config=-
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.oddin.org"]
      endpoint = ["http://localhost:30008"]
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "0.0.0.0"
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "0.0.0.0"
EOF

kubectx "$context=kind-$name"
