#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Generates a root certificate to be used within the cluster

Usage: generate-root-certificate [options]

Options:
  -h, --help          Show help options.
  -n, --name <VALUE>  Name for organization on the certificate [default: Example].
EOF
)"

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR/.." || exit 1

mkdir -p data/certs

KEY_PATH="data/certs/tls.key"
CRT_PATH="data/certs/tls.crt"

if [[ -e "$CRT_PATH" && -e "$KEY_PATH" ]]; then
	exit 0
fi

echo "Creating local root certificate..."
# NOTE: This certificate is used only for local development, you don't need to
# worry neither about creating certificate chains with intermediate certicates
# nor regarding the key length.
export name
cat config/certificate.conf.template | envsubst > data/certs/tls.conf
openssl req -x509 -sha256 -days 3650 -newkey rsa:2048 \
    -config data/certs/tls.conf -keyout "$KEY_PATH" \
    -out "$CRT_PATH" &> /dev/null

echo "Certificate successfully generated at: $CRT_PATH"
echo "Remeber to trust it"
