#!/bin/bash

DIR=$(readlink -f "$(dirname "$0")")

usage() {
  cat <<EOF
Installs dependencies needed for a well functioning local environment

Options:
  -h, --help Shows this message
EOF
}

cd "$DIR/.." || exit 1
mkdir -p data/certs
cd data/certs || exit 1

echo "Creating and trusting local root certificate..."
minica -ca-cert root.pem -ca-key root-key.pem -domains '*.oddin.localhost,oddin.localhost'
sudo mkdir -p /etc/ca-certificates/trust-source/anchors/
openssl x509 -outform der -in root.pem -out oddin-local.crt
sudo mv oddin-local.crt /etc/ca-certificates/trust-source/anchors/
sudo trust extract-compact
