#!/bin/bash

usage() {
  cat <<EOF
Manages the shared network used by the local environment

Usage:
  network <COMMAND>
  network --help

Options:
  -h, --help Shows this message

Commands:
  down Removes the shared network
  up   Creates the shared network
EOF
}

case "$1" in
  -h|--help)
    usage
    exit 0
    ;;
  down)
    docker network rm oddin-network
    ;;
  up)
    docker network create --attachable -d bridge oddin-network
    ;;
  *)
    echo "Invalid command"
    exit 1;
esac
