#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Installs components in the cluster

Usage: setup-cluster [options]

Options:
  -h, --help              Show help options.
  -d, --domain <VALUE>    Domain for your application [default: example.localhost].
  -r, --registry <VALUE>  Registry hostname with your images [default: registry.example.com].
  -p, --proxy <VALUE>     Whether or not to configure local registry as proxy [default: false].
EOF
)"

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR/.." || exit 1

echo "Installing Cert-Manager ..."
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml

echo "Waiting for Cert-Manager ..."
sleep 10 # k8s doesn't detect the resource sometimes
kubectl wait --namespace cert-manager \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/name=webhook \
  --timeout=5m > /dev/null

echo "Installing configuration package ..."
template=$(cat <<HEREDOC
{
	host: "$domain",
	registry: {host: "$registry", proxy: $proxy},
	cert: {crt: \$crt, key: \$key}
}
HEREDOC
)

jq -n \
  --rawfile crt data/certs/tls.crt \
  --rawfile key data/certs/tls.key \
  "$template" > data/values.json

# FIXME: We need to wait for traefik also
# > error: unable to recognize "STDIN": no matches for kind "Middleware" in version "traefik.containo.us/v1alpha1"
kct compile kcp -i data/values.json | tee data/rendered.yaml | kubectl apply --validate=false -f -
