#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Installs components in the cluster for TLS

Usage: setup-cluster [options]

Options:
  -h, --help  Show help options.
EOF
)"

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR/.." || exit 1

echo "Installing Contour ..."
kubectl apply --validate=false -f https://projectcontour.io/quickstart/contour.yaml
echo "Installing Cert-Manager ..."
kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.0.4/cert-manager.yaml

echo "Waiting for Cert-Manager ..."
sleep 10 # k8s doesn't detect the resource sometimes
kubectl wait --namespace cert-manager \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/name=cert-manager \
  --timeout=5m > /dev/null

echo "Installing certificate and registry ..."
template='{registry: "registry.oddin.org", domain: "oddin.localhost", ca: {crt: $crt, key: $key}}'
jq -n \
  --rawfile crt data/certs/tls.crt \
  --rawfile key data/certs/tls.key \
  "$template" | kct compile kcp -i - | kubectl apply -f -
