#!/usr/bin/env bash

set -o errexit

eval "$(docopts -h - : "$@" <<EOF
Installs components in the cluster

Usage: setup-cluster [options]

Options:
  -h, --help          Show help options.
  -n, --name <VALUE>  The part before the tld in the domain [default: oddin].
  -t, --tld <VALUE>   TLD for your public domain [default: org].
EOF
)"

DIR=$(readlink -f "$(dirname "$0")")
cd "$DIR/.." || exit 1

echo "Installing Cert-Manager ..."
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml

echo "Waiting for Cert-Manager ..."
sleep 10 # k8s doesn't detect the resource sometimes
kubectl wait --namespace cert-manager \
  --for=condition=ready pod \
  --selector=app.kubernetes.io/name=webhook \
  --timeout=5m > /dev/null

echo "Installing configuration package ..."
template="{name: \"$name\", tld: \"$tld\", ca: {crt: \$crt, key: \$key}}"
jq -n \
  --rawfile crt data/certs/tls.crt \
  --rawfile key data/certs/tls.key \
  "$template" > data/values.json

kct compile kcp -i data/values.json | tee data/rendered.yaml | kubectl apply -f -
