apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine
  labels:
    app.kubernetes.io/name: alpine
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alpine
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alpine
    spec:
      containers:
      - name: alpine
        image: alpine
        command: ['sh']
        args: ['-c', 'sleep infinity']
